### ISSUE TITLE
masks to cucumbers are rectangles

### ISSUE THREAD

**Issue by AsherYartsevTech** [AsherYartsevTech/Mask_RCNN#2]
for now, when I use some online tool to make transparent background - the draw_mask algorithm won't digest it well

<img width="1135" alt="screen shot 2018-12-05 at 15 35 20" src="https://user-images.githubusercontent.com/45081186/49516917-702aa200-f8a3-11e8-8605-44a44d9e8495.png">

**Comment by simonlousky** [comment]
mask was being taken from the black pixels of the RGB channels instead of the alpha channel.
rectified in #5fba387
